/** Статичтные названия функици */
export const FETCH_ACCIDENTS_EPIC = "GET/FETCH_ACCIDENTS_EPIC";
export const FETCH_FILTER_ACCIDENTS_EPIC = "GET/FETCH_FILTER_ACCIDENTS_EPIC";

export const SET_ACCIDENTS_DATA = "SET_ACCIDENTS_DATA";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_DAYTIME = "SET_SELECTED_DAYTIME";
export const SET_SELECTED_DISTRICS = "SET_SELECTED_DISTRICS";
export const SET_SELECTED_AGENCIES = "SET_SELECTED_AGENCIES";
export const SET_SELECTED_LOCATIONS = "SET_SELECTED_LOCATIONS";
export const SET_SELECTED_VIOLATIONS = "SET_SELECTED_VIOLATIONS";
export const SET_SELECTED_ANOTHER = "SET_SELECTED_ANOTHER";

export const FILTER_ACCIDENTS_DATA = "FILTER_ACCIDENTS_DATA";
export const RESET_FILTERS = "RESET_FILTERS";
export const RESET_ALL = "RESET_ALL";
export const SET_FILTER_VALUE = "SET_FILTER_VALUE";
